<?xml version="1.0" encoding="utf-8"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="quadrotor_generic"
        params="ARM_X:=0.1 ARM_Y:=0.1 ARM_Z:=0.03 MASS:=1.0 IXX:=0.0025 IYY:=0.0025 IZZ:=0.005 base_color:='0.5 0.5 0.5 1.0' prop_color:='0.8 0.0 0.0 0.8'">
        <link name="base_link">

            <inertial>
                <origin rpy="0 0 0" xyz="0 0 0" />
                <mass value="${MASS}" />
                <inertia ixx="${IXX}" ixy="0.0" ixz="0.0" iyy="${IYY}" iyz="0.0" izz="${IZZ}" />
            </inertial>

            <visual>
                <origin rpy="0 0 0" xyz="0 0 0" />
                <geometry>
                    <cylinder radius="${0.2*sqrt(ARM_X**2+ARM_Y**2)}" length="${0.7*ARM_Z}" />
                </geometry>
                <material name="base_mat">
                    <color rgba="${base_color}" />
                </material>
            </visual>

            <!-- Rotor 1 -->
            <visual>
                <origin xyz="${ARM_X/2} ${ARM_Y/2} 0" rpy="0 0 ${-atan(ARM_X/ARM_Y)}" />
                <geometry>
                    <box
                        size="${0.15* sqrt(ARM_X**2+ARM_Y**2)} ${sqrt(ARM_X**2+ARM_Y**2)} ${0.5*ARM_Z}" />
                </geometry>
            </visual>
            <visual>
                <origin xyz="${ARM_X} ${ARM_Y} ${ARM_Z/2}" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${0.2*ARM_Z}" length="${ARM_Z}" />
                </geometry>
            </visual>

            <!-- Rotor 2 -->
            <visual>
                <origin xyz="${-ARM_X/2} ${ARM_Y/2} 0" rpy="0 0 ${-atan(-ARM_X/ARM_Y)}" />
                <geometry>
                    <box
                        size="${0.15* sqrt(ARM_X**2+ARM_Y**2)} ${sqrt(ARM_X**2+ARM_Y**2)} ${0.5*ARM_Z}" />
                </geometry>
            </visual>
            <visual>
                <origin xyz="${-ARM_X} ${ARM_Y} ${ARM_Z/2}" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${0.2*ARM_Z}" length="${ARM_Z}" />
                </geometry>
            </visual>

            <!-- Rotor 3 -->
            <visual>
                <origin xyz="${-ARM_X/2} ${-ARM_Y/2} 0" rpy="0 0 ${-atan(ARM_X/ARM_Y)}" />
                <geometry>
                    <box
                        size="${0.15* sqrt(ARM_X**2+ARM_Y**2)} ${sqrt(ARM_X**2+ARM_Y**2)} ${0.5*ARM_Z}" />
                </geometry>
            </visual>
            <visual>
                <origin xyz="${-ARM_X} ${-ARM_Y} ${ARM_Z/2}" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${0.2*ARM_Z}" length="${ARM_Z}" />
                </geometry>
            </visual>

            <!-- Rotor 4 -->
            <visual>
                <origin xyz="${ARM_X/2} ${-ARM_Y/2} 0" rpy="0 0 ${-atan(-ARM_X/ARM_Y)}" />
                <geometry>
                    <box
                        size="${0.15* sqrt(ARM_X**2+ARM_Y**2)} ${sqrt(ARM_X**2+ARM_Y**2)} ${0.5*ARM_Z}" />
                </geometry>
            </visual>
            <visual>
                <origin xyz="${ARM_X} ${-ARM_Y} ${ARM_Z/2}" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${0.2*ARM_Z}" length="${ARM_Z}" />
                </geometry>
            </visual>

            <collision>
                <origin rpy="0 0 0" xyz="0 0 ${ARM_Z/2}" />
                <geometry>
                    <cylinder radius="${sqrt(ARM_X**2+ARM_Y**2)}" length="${ARM_Z}" />
                </geometry>
            </collision>

        </link>

        <link name="prop0_link">
            <inertial>
                <origin rpy="0 0 0" xyz="${ARM_X} -${ARM_Y} ${ARM_Z}" />
                <mass value="0" />
                <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
            </inertial>
            <visual>
                <origin xyz="${ARM_X} -${ARM_Y} ${ARM_Z}" rpy="0.0 0.0 0.0" />
                <geometry>
                    <cylinder radius="${0.7*ARM_X}" length="${0.1*ARM_Z}" />
                </geometry>
                <material name='prop_mat'>
                    <color rgba="${prop_color}" />
                </material>
            </visual>
        </link>
        <joint name="prop0_joint" type="fixed">
            <parent link="base_link" />
            <child link="prop0_link" />
        </joint>


        <link name="prop1_link">
            <inertial>
                <origin rpy="0 0 0" xyz="${ARM_X} ${ARM_Y} ${ARM_Z}" />
                <mass value="0" />
                <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
            </inertial>
            <visual>
                <origin xyz="${ARM_X} ${ARM_Y} ${ARM_Z}" rpy="0.0 0.0 0.0" />
                <geometry>
                    <cylinder radius="${0.7*ARM_X}" length="${0.1*ARM_Z}" />
                </geometry>
                <material name='prop_mat'>
                    <color rgba="${prop_color}" />
                </material>
            </visual>
        </link>
        <joint name="prop1_joint" type="fixed">
            <parent link="base_link" />
            <child link="prop1_link" />
        </joint>

        <link name="prop2_link">
            <inertial>
                <origin rpy="0 0 0" xyz="-${ARM_X} ${ARM_Y} ${ARM_Z}" />
                <mass value="0" />
                <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
            </inertial>
            <visual>
                <origin xyz="-${ARM_X} ${ARM_Y} ${ARM_Z}" rpy="0.0 0.0 0.0" />
                <geometry>
                    <cylinder radius="${0.7*ARM_X}" length="${0.1*ARM_Z}" />
                </geometry>
                <material name='prop_mat'>
                    <color rgba="${prop_color}" />
                </material>
            </visual>
        </link>
        <joint name="prop2_joint" type="fixed">
            <parent link="base_link" />
            <child link="prop2_link" />
        </joint>

        <link name="prop3_link">
            <inertial>
                <origin rpy="0 0 0" xyz="-${ARM_X} -${ARM_Y} ${ARM_Z}" />
                <mass value="0" />
                <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
            </inertial>
            <visual>
                <origin xyz="-${ARM_X} -${ARM_Y} ${ARM_Z}" rpy="0.0 0.0 0.0" />
                <geometry>
                    <cylinder radius="${0.7*ARM_X}" length="${0.1*ARM_Z}" />
                </geometry>
                <material name='prop_mat'>
                    <color rgba="${prop_color}" />
                </material>
            </visual>
        </link>

        <joint name="prop3_joint" type="fixed">
            <parent link="base_link" />
            <child link="prop3_link" />
        </joint>
    </xacro:macro>
</robot>